vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        article:
            uri_prefix: /file/images/article
            upload_destination: '%kernel.project_dir%/public/file/images/article'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        video_image:
            uri_prefix: /file/images/videoimage
            upload_destination: '%kernel.project_dir%/public/file/images/video'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        video:
            uri_prefix: /file/video
            upload_destination: '%kernel.project_dir%/public/file/video'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

